version: "3.7"
services: 
    app:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports: 
            - 8080:8080
        restart: always
        depends_on:
            - db
    
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        volumes: 
        - ./mysql-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: backend